package com.vintage.datahelper.model.mapper;

import com.vintage.datahelper.model.entity.CountryLanguage;
import com.vintage.datahelper.model.entity.CountryLanguageKey;

public interface CountryLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int insert(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int insertSelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    CountryLanguage selectByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CountryLanguage record);
}